<a href="https://colab.research.google.com/github/MamatkulovBunyodbek1999/My-portfoilio-samples/blob/main/Tashkent.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

![Imgur](https://i.imgur.com/5pXzCIu.png)

# Data Science and Artificial intelligence  Practikum

## 5-MODUL. Machine Learning. 

### Internship. Simple Linear Regression


# Housing price prediction project

![Imgur](https://assets.weforum.org/community/image/9hPlWcbYTih12mJwMxQ86V9WumxZtXJX89-sHyhfF2I.jpeg)

# First of all i will Import python libraries. 

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
%matplotlib inline
import seaborn as sns
import sklearn # scikit-learn library

# Importing data

In [3]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/housing_data_08-02-2021.csv')
df.head(5)

location       district  rooms  \
0  город Ташкент, Юнусабадский район, Юнусабад 8-...   Юнусабадский      3   
1  город Ташкент, Яккасарайский район, 1-й тупик ...  Яккасарайский      2   
2  город Ташкент, Чиланзарский район, Чиланзар 2-...   Чиланзарский      2   
3  город Ташкент, Чиланзарский район, Чиланзар 9-...   Чиланзарский      3   
4  город Ташкент, Чиланзарский район, площадь Актепа   Чиланзарский      3   

  size  level  max_levels  price  
0   57      4           4  52000  
1   52      4           5  56000  
2   42      4           4  37000  
3   65      1           4  49500  
4   70      3           5  55000

# Cleaning data 

In [4]:
df = df[df.price !='Договорная']

In [5]:
df['price'] = df['price'].astype('int')

In [6]:
df["price"].value_counts()

35000     158
45000     157
55000     155
42000     152
40000     137
         ... 
46200       1
111000      1
48499       1
49994       1
22914       1
Name: price, Length: 716, dtype: int64

In [7]:
df.loc[df['size'] == 'Площадьземли:1сот']

location     district  rooms  \
5347  город Ташкент, Яшнободский район, Дархон  Яшнободский      4   

                   size  level  max_levels   price  
5347  Площадьземли:1сот      3           5  150000

In [8]:
df.drop(labels=5347, inplace=True)

In [9]:
df['size'] = df['size'].astype('float64')

In [10]:
df["size"].value_counts()

70.00     376
60.00     374
50.00     334
65.00     255
80.00     250
         ... 
88.90       1
49.88       1
56.97       1
129.18      1
27.50       1
Name: size, Length: 404, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7465 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   location    7465 non-null   object 
 1   district    7465 non-null   object 
 2   rooms       7465 non-null   int64  
 3   size        7465 non-null   float64
 4   level       7465 non-null   int64  
 5   max_levels  7465 non-null   int64  
 6   price       7465 non-null   int64  
dtypes: float64(1), int64(4), object(2)
memory usage: 466.6+ KB


In [12]:
df['size'] = df['size'].astype(np.int64)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7465 entries, 0 to 7564
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   location    7465 non-null   object
 1   district    7465 non-null   object
 2   rooms       7465 non-null   int64 
 3   size        7465 non-null   int64 
 4   level       7465 non-null   int64 
 5   max_levels  7465 non-null   int64 
 6   price       7465 non-null   int64 
dtypes: int64(5), object(2)
memory usage: 466.6+ KB


In [14]:
df.shape

(7465, 7)

In [15]:
df.head()

location       district  rooms  \
0  город Ташкент, Юнусабадский район, Юнусабад 8-...   Юнусабадский      3   
1  город Ташкент, Яккасарайский район, 1-й тупик ...  Яккасарайский      2   
2  город Ташкент, Чиланзарский район, Чиланзар 2-...   Чиланзарский      2   
3  город Ташкент, Чиланзарский район, Чиланзар 9-...   Чиланзарский      3   
4  город Ташкент, Чиланзарский район, площадь Актепа   Чиланзарский      3   

   size  level  max_levels  price  
0    57      4           4  52000  
1    52      4           5  56000  
2    42      4           4  37000  
3    65      1           4  49500  
4    70      3           5  55000

In [16]:
df.isnull().sum()

location      0
district      0
rooms         0
size          0
level         0
max_levels    0
price         0
dtype: int64

In [17]:
df.shape

(7465, 7)

In [18]:
df=df.drop_duplicates()
df.shape

(6766, 7)

#Starting point of our ML model with clean data

In [19]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

X_train = train_set.drop("price", axis=1)
y = train_set["price"].copy()

X_num = X_train.drop(['location', 'district'], axis=1)

# Building Pipeline 

###Pipeline for numeric columns 

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OrdinalEncoder
from sklearn.preprocessing import MinMaxScaler
            


In [21]:
num_pipeline = Pipeline([
          ('imputer', SimpleImputer(strategy='median')),
          ('min_max_scaler', MinMaxScaler())
])

###Pipeline for string columns 

In [22]:
from sklearn.compose import ColumnTransformer

num_attribs = list(X_num)
cat_attribs = ['location', 'district']

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs),
    ('cat', OrdinalEncoder(), cat_attribs)
])

In [23]:
X_prepared = full_pipeline.fit_transform(X_train)

In [24]:
X_prepared[0:5,:]

array([[1.11111111e-01, 7.71439592e-04, 1.66666667e-01, 1.25000000e-01,
        3.03000000e+02, 2.00000000e+00],
       [2.22222222e-01, 9.85728368e-04, 1.11111111e-01, 1.25000000e-01,
        4.29000000e+02, 3.00000000e+00],
       [1.11111111e-01, 7.85725510e-04, 1.11111111e-01, 1.66666667e-01,
        6.08000000e+02, 5.00000000e+00],
       [0.00000000e+00, 4.14291633e-04, 1.11111111e-01, 1.66666667e-01,
        7.82000000e+02, 6.00000000e+00],
       [2.22222222e-01, 1.37144816e-03, 0.00000000e+00, 2.91666667e-01,
        8.00000000e+02, 6.00000000e+00]])

#Machine Learning

In [25]:
from sklearn.linear_model import LinearRegression

LR_model = LinearRegression()

In [26]:
LR_model.fit(X_prepared, y)

LinearRegression()

# Testing ML model

In [27]:
test_data = X_train.sample(5)
test_data

location       district  rooms  \
1623    город Ташкент, Олмазорский район, Каракамыш-2/3    Олмазорский      2   
1906          город Ташкент, Яккасарайский район, Ракат  Яккасарайский      2   
3024       город Ташкент, Чиланзарский район, Наккошлык   Чиланзарский      3   
4793     город Ташкент, Чиланзарский район, Сугалли-ота   Чиланзарский      3   
5115  город Ташкент, Яккасарайский район, Шота Руста...  Яккасарайский      3   

      size  level  max_levels  
1623    56      4           4  
1906    36      1           4  
3024    60      4           5  
4793    59      3           5  
5115    70      3           4

In [28]:
test_label = y.loc[test_data.index]
test_label

1623    32200
1906    30000
3024    47000
4793    49500
5115    68000
Name: price, dtype: int64

In [29]:
test_data_prepared = full_pipeline.transform(test_data)
test_data_prepared

array([[1.11111111e-01, 7.85725510e-04, 1.66666667e-01, 1.25000000e-01,
        4.29000000e+02, 3.00000000e+00],
       [1.11111111e-01, 5.00007143e-04, 0.00000000e+00, 1.25000000e-01,
        1.14100000e+03, 9.00000000e+00],
       [2.22222222e-01, 8.42869184e-04, 1.66666667e-01, 1.66666667e-01,
        6.97000000e+02, 6.00000000e+00],
       [2.22222222e-01, 8.28583265e-04, 1.11111111e-01, 1.66666667e-01,
        7.10000000e+02, 6.00000000e+00],
       [2.22222222e-01, 9.85728368e-04, 1.11111111e-01, 1.25000000e-01,
        1.17600000e+03, 9.00000000e+00]])

In [30]:
predicted_data = LR_model.predict(test_data_prepared)
predicted_data

array([30616.30618871, 56563.18097664, 95448.30070532, 98119.27427646,
       71381.45136588])

In [32]:
pd.DataFrame({'Predicted price':predicted_data, 'Real price': test_label})

Predicted price  Real price
1623     30616.306189       32200
1906     56563.180977       30000
3024     95448.300705       47000
4793     98119.274276       49500
5115     71381.451366       68000

#5-STEP. Model evaluation 

In [33]:
test_set

location           district  \
467   город Ташкент, Мирзо-Улугбекский район, ц-1 Бу...  Мирзо-Улугбекский   
7224      город Ташкент, Учтепинский район, Чиланзар-11        Учтепинский   
220   город Ташкент, Мирзо-Улугбекский район, Паркен...  Мирзо-Улугбекский   
4703         город Ташкент, Яккасарайский район, Глинки      Яккасарайский   
549   город Ташкент, Мирзо-Улугбекский район, Карасу...  Мирзо-Улугбекский   
...                                                 ...                ...   
3469  город Ташкент, Юнусабадский район, Юнусабад 6-...       Юнусабадский   
3754          город Ташкент, Мирабадский район, Мирабад        Мирабадский   
1173  город Ташкент, Учтепинский район, Чиланзар 14-...        Учтепинский   
843   город Ташкент, Чиланзарский район, Чиланзар 17...       Чиланзарский   
1183           город Ташкент, Учтепинский район, Такачи        Учтепинский   

      rooms  size  level  max_levels   price  
467       4    90      3           4  133000  
7224      2    51      2           4       2  
220       2    63      4           9   55500  
4703      4   250      4           8  250000  
549       4    91      3           5   50000  
...     ...   ...    ...         ...     ...  
3469      2    74      3           6   46835  
3754      3    72      2           9   82000  
1173      2    50      2           4   33999  
843       3    65      4           4   46500  
1183      2    54      3           5   37000  

[1354 rows x 7 columns]

In [34]:
X_test = test_set.drop('price', axis=1)
X_test

location           district  \
467   город Ташкент, Мирзо-Улугбекский район, ц-1 Бу...  Мирзо-Улугбекский   
7224      город Ташкент, Учтепинский район, Чиланзар-11        Учтепинский   
220   город Ташкент, Мирзо-Улугбекский район, Паркен...  Мирзо-Улугбекский   
4703         город Ташкент, Яккасарайский район, Глинки      Яккасарайский   
549   город Ташкент, Мирзо-Улугбекский район, Карасу...  Мирзо-Улугбекский   
...                                                 ...                ...   
3469  город Ташкент, Юнусабадский район, Юнусабад 6-...       Юнусабадский   
3754          город Ташкент, Мирабадский район, Мирабад        Мирабадский   
1173  город Ташкент, Учтепинский район, Чиланзар 14-...        Учтепинский   
843   город Ташкент, Чиланзарский район, Чиланзар 17...       Чиланзарский   
1183           город Ташкент, Учтепинский район, Такачи        Учтепинский   

      rooms  size  level  max_levels  
467       4    90      3           4  
7224      2    51      2           4  
220       2    63      4           9  
4703      4   250      4           8  
549       4    91      3           5  
...     ...   ...    ...         ...  
3469      2    74      3           6  
3754      3    72      2           9  
1173      2    50      2           4  
843       3    65      4           4  
1183      2    54      3           5  

[1354 rows x 6 columns]

In [35]:
y_test = test_set['price'].copy()
y_test

467     133000
7224         2
220      55500
4703    250000
549      50000
         ...  
3469     46835
3754     82000
1173     33999
843      46500
1183     37000
Name: price, Length: 1354, dtype: int64

In [36]:
X_test_prepared = full_pipeline.fit_transform(X_test)

In [38]:
y_predicted = LR_model.predict(X_test_prepared)

In [39]:
from sklearn.metrics import mean_squared_error
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE 
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

126522.96368690934


#DecisionTree

![Imgur](https://media.geeksforgeeks.org/wp-content/cdn-uploads/Decision_Tree-2.png)

In [40]:
from sklearn.tree import DecisionTreeRegressor
Tree_model = DecisionTreeRegressor()
Tree_model.fit(X_prepared, y)

DecisionTreeRegressor()

In [41]:
y_predicted = Tree_model.predict(X_test_prepared)

In [42]:
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

592792.9765436198


#RandomForest
![Imgur](https://upload.wikimedia.org/wikipedia/commons/7/76/Random_forest_diagram_complete.png)

In [43]:
from sklearn.ensemble import RandomForestRegressor
RF_model = RandomForestRegressor()
RF_model.fit(X_prepared, y)

RandomForestRegressor()

In [44]:
y_predicted = RF_model.predict(X_test_prepared)
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

222438.8771563831


#Cross-Validation 
![Imgur](https://dataaspirant.com/wp-content/uploads/2020/12/1-Cross-Validation.png)

In [45]:
X = df.drop("price", axis=1)
y = df["price"].copy()

X_prepared = full_pipeline.fit_transform(X)

In [46]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Std.dev:", scores.std())

#Cross-validation

In [47]:
from sklearn.model_selection import cross_val_score

#LogisticRegression
![Imgur](https://miro.medium.com/max/640/0*gKOV65tvGfY8SMem.png)

In [48]:
scores = cross_val_score(LR_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)

In [49]:
display_scores(LR_rmse_scores)

Scores: [  72229.14553032   41796.02046167  150226.54234544   42783.89436637
   41056.67353391   48834.13991728   52224.97830919 1996439.11124427
  173778.37892516  681114.85272221]
Mean: 330048.3737355807
Std.dev: 585553.2859515554


#Decision Tree

In [50]:
scores = cross_val_score(Tree_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)

Scores: [ 157660.86531327 1997675.05387519  257695.85038236   60410.00249988
 2031528.7428437    35731.00014994   70109.21557536 2084653.17622696
  666903.47907361  700343.95525024]
Mean: 806271.1341190515
Std.dev: 836612.7827487631


#Random Forest
![Imgur](https://miro.medium.com/max/5752/1*5dq_1hnqkboZTcKFfwbO9A.png)

In [51]:
scores = cross_val_score(RF_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)


Scores: [  75087.78021729  627087.99555235  200079.61654898  192784.57216343
 1204829.07326301   37664.8625158   360999.17060106 2010147.10751447
  300991.45612278  701846.5283425 ]
Mean: 571151.8162841651
Std.dev: 584906.7651648693


#PROJECT HAS NOT BEEN COMPLETED